name: "Audio2MIDITransformer"

params:
  d_model: 1025
  n_notes: 88
  nhead_encoder: 5
  nhead_decoder: 11
  num_encoder_layers: 6
  num_decoder_layers: 6
  dim_feedforward: 2048
  max_len: 12
  tgt_max_len: 4
  batch_first: false
