name: "AudioTransformer"

params:
  d_model: 1024
  hidden_dims: [512, 256]
  n_notes: 88
  nhead_encoder: 16
  nhead_decoder: 11
  num_encoder_layers: 1
  num_decoder_layers: 1
  dim_feedforward_encoder: 2048
  dim_feedforward_decoder: 256
  batch_first: false
